#!/usr/bin/env bash
# owner: project-infrastructure
# scope: plugin-only
# _smoke-test-source-languages.sh — Unit-tier tests for language-aware
# Check 3 ownership (#859): source_languages enforcement, in-file marker
# ownership, the unknown-prefix diagnostic, and Half C undeclared-source-type
# discovery. Picked up automatically by ci-checks.sh's === Smoke tests === loop.
set -uo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HC="$ROOT/scripts/health-check.sh"
FAILED=0
pass() { echo "  PASS: $1"; }
fail_case() { echo "  FAIL: $1"; FAILED=1; }

# Minimal Check-1-complete fixture rooted at a fresh mktemp dir. Echoes the dir.
make_fixture() {
  local d; d="$(mktemp -d)"
  mkdir -p "$d/docs/specs" "$d/docs/definitions" "$d/src" "$d/workflows"
  touch "$d/CLAUDE.md" "$d/contracts.yaml" "$d/docs/ARCHITECTURE.md" "$d/workflows/README.md"
  (cd "$d" && git init -q && git config user.email t@t && git config user.name t)
  printf '%s\n' "# Project Register" "" "## Spec Index" "" \
    "| Spec | Status | Owner | Owns (files/directories) |" \
    "|------|--------|-------|--------------------------|" > "$d/docs/REGISTER.md"
  printf '%s\n' "$d"
}

# Append a spec + REGISTER row owning a file/dir pattern.
add_spec_owning() {  # <dir> <spec-name> <owns-pattern>
  local d="$1" name="$2" owns="$3"
  cat > "$d/docs/specs/$name.spec.md" <<INNER
---
name: $name
status: active
owner: architecture
owns:
  - $owns
---

# $name
INNER
  echo "| $name.spec.md | active | architecture | $owns |" >> "$d/docs/REGISTER.md"
}

# --- Task 2: backward-compat default + opt-in enforcement ---

test_default_does_not_scan_ts() {
  local d; d="$(make_fixture)"
  add_spec_owning "$d" alpha "src/alpha.py"
  echo "# owner: alpha" > "$d/src/alpha.py"
  echo "// not owned by anything" > "$d/src/stray.ts"   # unowned .ts
  (cd "$d" && git add -A && git commit -qm init)
  local out; out="$(bash "$HC" "$d" 2>&1)"
  if echo "$out" | grep -q "Unowned:.*stray.ts"; then
    fail_case "default config flagged stray.ts (should scan only .py)"
  else
    pass "default source_languages=[py] does not scan .ts"
  fi
  rm -rf "$d"
}

test_optin_flags_unowned_ts() {
  local d; d="$(make_fixture)"
  printf 'source_languages:\n  - py\n  - ts\n' > "$d/.arboretum.yml"
  add_spec_owning "$d" alpha "src/alpha.py"
  echo "# owner: alpha" > "$d/src/alpha.py"
  echo "// not owned by anything" > "$d/src/stray.ts"
  (cd "$d" && git add -A && git commit -qm init)
  local out; out="$(bash "$HC" "$d" 2>&1)"
  if echo "$out" | grep -q "Unowned:.*stray.ts"; then
    pass "source_languages:[py,ts] flags unowned .ts"
  else
    fail_case "opt-in did not flag unowned stray.ts"
  fi
  rm -rf "$d"
}

# --- Task 3: in-file leading-block owner markers count as ownership ---

test_marker_owns_enforced_sql() {
  local d; d="$(make_fixture)"
  printf 'source_languages:\n  - py\n  - sql\n' > "$d/.arboretum.yml"
  add_spec_owning "$d" qsql "src/q.sql"          # spec exists; resolvable
  # File NOT under any owns: pattern, owned purely by its in-file marker:
  cat > "$d/src/loose.sql" <<'INNER'
-- owner: qsql
SELECT 1;
INNER
  (cd "$d" && git add -A && git commit -qm init)
  local out; out="$(bash "$HC" "$d" 2>&1)"
  if echo "$out" | grep -q "Unowned:.*loose.sql"; then
    fail_case "in-file -- owner: marker did not satisfy ownership"
  else
    pass "leading-block -- owner: marker counts as ownership"
  fi
  rm -rf "$d"
}

test_generated_banner_marker_owns() {
  local d; d="$(make_fixture)"
  printf 'source_languages:\n  - py\n  - sql\n' > "$d/.arboretum.yml"
  add_spec_owning "$d" qsql "src/q.sql"
  # owner: line follows a DO-NOT-EDIT banner line — leading-block scan must find it
  cat > "$d/src/gen.sql" <<'INNER'
-- DO NOT EDIT — generated by build.py
-- owner: qsql
-- generated-at: abc123
SELECT 2;
INNER
  (cd "$d" && git add -A && git commit -qm init)
  local out; out="$(bash "$HC" "$d" 2>&1)"
  if echo "$out" | grep -q "Unowned:.*gen.sql"; then
    fail_case "generated provenance banner owner line not detected"
  else
    pass "generated banner owner line detected in leading block"
  fi
  rm -rf "$d"
}

test_crlf_marker_owns() {
  local d; d="$(make_fixture)"
  printf 'source_languages:\n  - py\n  - sql\n' > "$d/.arboretum.yml"
  add_spec_owning "$d" qsql "src/q.sql"
  # CRLF line endings (Windows-authored): the marker must still resolve (#859 B4).
  printf -- '-- owner: qsql\r\nSELECT 1;\r\n' > "$d/src/crlf.sql"
  (cd "$d" && git add -A && git commit -qm init)
  local out; out="$(bash "$HC" "$d" 2>&1)"
  if echo "$out" | grep -q "Unowned:.*crlf.sql"; then
    fail_case "CRLF-terminated -- owner: marker flagged Unowned (trailing \\r not stripped)"
  else
    pass "CRLF-terminated owner marker resolves (\\r stripped)"
  fi
  rm -rf "$d"
}

test_php_opener_marker_owns() {
  local d; d="$(make_fixture)"
  printf 'source_languages:\n  - py\n  - php\n' > "$d/.arboretum.yml"
  add_spec_owning "$d" papp "src/p.php"
  # PHP files open with <?php before the // owner: line (#859 B4 / Copilot).
  printf '<?php\n// owner: papp\necho 1;\n' > "$d/src/loose.php"
  (cd "$d" && git add -A && git commit -qm init)
  local out; out="$(bash "$HC" "$d" 2>&1)"
  if echo "$out" | grep -q "Unowned:.*loose.php"; then
    fail_case "// owner: after <?php opener not detected"
  else
    pass "PHP <?php opener skipped; // owner: marker detected"
  fi
  rm -rf "$d"
}

test_php_cli_shebang_opener_marker_owns() {
  local d; d="$(make_fixture)"
  printf 'source_languages:\n  - py\n  - php\n' > "$d/.arboretum.yml"
  add_spec_owning "$d" papp "src/p.php"
  # PHP CLI: shebang line 1, <?php opener line 2, // owner: line 3 (#859 B4 / Codex P2).
  printf '#!/usr/bin/env php\n<?php\n// owner: papp\necho 1;\n' > "$d/src/cli.php"
  (cd "$d" && git add -A && git commit -qm init)
  local out; out="$(bash "$HC" "$d" 2>&1)"
  if echo "$out" | grep -q "Unowned:.*cli.php"; then
    fail_case "PHP opener after shebang not skipped; // owner: missed"
  else
    pass "PHP shebang+<?php opener skipped; // owner: detected"
  fi
  rm -rf "$d"
}

test_bad_marker_still_unowned() {
  local d; d="$(make_fixture)"
  printf 'source_languages:\n  - py\n  - sql\n' > "$d/.arboretum.yml"
  cat > "$d/src/orphan.sql" <<'INNER'
-- owner: nonexistent-spec
SELECT 3;
INNER
  (cd "$d" && git add -A && git commit -qm init)
  local out; out="$(bash "$HC" "$d" 2>&1)"
  if echo "$out" | grep -q "Unowned:.*orphan.sql"; then
    pass "marker to nonexistent spec is still unowned"
  else
    fail_case "orphan.sql with unresolvable owner was not flagged"
  fi
  rm -rf "$d"
}

# --- Task 4: unknown-prefix diagnostic (advisory, config-driven) ---

test_unknown_prefix_diagnostic() {
  local d; d="$(make_fixture)"
  printf 'source_languages:\n  - py\n  - xyz\n' > "$d/.arboretum.yml"
  (cd "$d" && git add -A && git commit -qm init)
  local out rc
  out="$(bash "$HC" "$d" 2>&1)"; rc=$?
  if echo "$out" | grep -qi "xyz.*no comment prefix"; then
    pass "unknown enforced language emits a prefix diagnostic"
  else
    fail_case "no diagnostic for enforced language 'xyz' lacking a prefix"
  fi
  # config-only: the diagnostic is advisory, so it must NOT block (exit != 1)
  if [ "$rc" = "1" ]; then
    fail_case "unknown-prefix diagnostic incorrectly blocking (exit 1)"
  else
    pass "unknown-prefix diagnostic is advisory (exit $rc)"
  fi
  rm -rf "$d"
}

# --- Task 5: Half C undeclared-source-type discovery (advisory) ---

test_halfc_warns_undeclared_sql() {
  local d; d="$(make_fixture)"   # no .arboretum.yml → default [py]
  echo "SELECT 1;" > "$d/src/a.sql"
  echo "SELECT 2;" > "$d/src/b.sql"
  (cd "$d" && git add -A && git commit -qm init)
  local out; out="$(bash "$HC" "$d" 2>&1)"
  local n; n="$(echo "$out" | grep -c "not declared in source_languages")"
  if echo "$out" | grep -q "sql.*not declared in source_languages" && [ "$n" -eq 1 ]; then
    pass "Half C warns once for undeclared .sql with a count"
  else
    fail_case "Half C did not emit exactly one undeclared-.sql nudge (got $n)"
  fi
  rm -rf "$d"
}

test_halfc_silenced_by_ignore() {
  local d; d="$(make_fixture)"
  printf 'source_languages_ignore:\n  - sql\n' > "$d/.arboretum.yml"
  echo "SELECT 1;" > "$d/src/a.sql"
  (cd "$d" && git add -A && git commit -qm init)
  if bash "$HC" "$d" 2>&1 | grep -q "sql.*not declared"; then
    fail_case "ignore-list did not silence Half C"
  else
    pass "source_languages_ignore silences Half C"
  fi
  rm -rf "$d"
}

test_halfc_quiet_for_py_sh_only() {
  local d; d="$(make_fixture)"
  add_spec_owning "$d" alpha "src/alpha.py"
  echo "# owner: alpha" > "$d/src/alpha.py"
  printf '#!/usr/bin/env bash\necho hi\n' > "$d/src/helper.sh"   # sh excluded from discovery
  (cd "$d" && git add -A && git commit -qm init)
  if bash "$HC" "$d" 2>&1 | grep -q "not declared in source_languages"; then
    fail_case "Half C nagged a .py+.sh-only repo (backward-compat break)"
  else
    pass "Half C silent for a .py+.sh-only repo"
  fi
  rm -rf "$d"
}

test_default_does_not_scan_ts
test_optin_flags_unowned_ts
test_marker_owns_enforced_sql
test_generated_banner_marker_owns
test_crlf_marker_owns
test_php_opener_marker_owns
test_php_cli_shebang_opener_marker_owns
test_bad_marker_still_unowned
test_unknown_prefix_diagnostic
test_halfc_warns_undeclared_sql
test_halfc_silenced_by_ignore
test_halfc_quiet_for_py_sh_only

[ "$FAILED" -eq 0 ] && echo "ALL PASS" || exit 1
