#!/usr/bin/env bash
# owner: pipeline-contracts-template
# generate-coverage.sh — Walk the filesystem and regenerate
# docs/contracts/_coverage.md as a deterministic table mapping every
# governance script/hook to its covering contract.
#
# Sources scanned (recursive):
#   scripts/**/*.sh                    (excluding any _* component in path)
#   .claude/hooks/**/*.sh
# Contracts read:
#   docs/contracts/*.contract.md       (full WS3a shape, owns: frontmatter)
#   docs/contracts/*.cli-contract.md   (lighter WS5 shape, script: frontmatter)
#
# Idempotent by construction: LC_ALL=C sort, no timestamps, stable formatting.
# Per WS5 design §D6. Portable: no GNU-specific find flags.
# Compatible with bash 3.2 (macOS default) — no declare -A.

set -uo pipefail
ROOT="$(pwd)"
OUT="$ROOT/docs/contracts/_coverage.md"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
YAML_LITE="$SCRIPT_DIR/lib/yaml-lite.sh"
if [ ! -f "$YAML_LITE" ] && [ -f "$ROOT/scripts/lib/yaml-lite.sh" ]; then
  YAML_LITE="$ROOT/scripts/lib/yaml-lite.sh"
fi
[ -f "$YAML_LITE" ] || { echo "generate-coverage: yaml-lite helper not found" >&2; exit 1; }
# shellcheck source=scripts/lib/yaml-lite.sh
. "$YAML_LITE"
mkdir -p "$(dirname "$OUT")"

# Helper: list source files under a root, relative to it, excluding any _* component
list_sources() {
  local base="$1"
  [ -d "$base" ] || return 0
  ( cd "$base" && find . -type f -name '*.sh' -print 2>/dev/null ) \
    | sed 's|^\./||' \
    | grep -v -E '(^|/)_' \
    | LC_ALL=C sort
}

scripts=$(list_sources "$ROOT/scripts")
hooks=$(list_sources "$ROOT/.claude/hooks")

contract_rows_tmp=$(mktemp)
trap 'rm -f "$contract_rows_tmp"' EXIT

if [ -d "$ROOT/docs/contracts" ]; then
  for contract_path in "$ROOT"/docs/contracts/*.md; do
    [ -f "$contract_path" ] || continue
    case "$contract_path" in
      *.contract.md) shape="full" ;;
      *.cli-contract.md) shape="cli" ;;
      *) continue ;;
    esac
    rel_contract=${contract_path#"$ROOT"/}
    parsed=$(yaml_lite_parse frontmatter "$contract_path" 2>/dev/null) || continue
    if [ "$shape" = "cli" ]; then
      script_value=$(printf '%s\n' "$parsed" | awk -F= '$1 == "script" { print substr($0, index($0, "=") + 1); exit }')
      [ -n "$script_value" ] && printf '%s|%s|%s\n' "$script_value" "$rel_contract" "$shape" >> "$contract_rows_tmp"
    else
      printf '%s\n' "$parsed" | awk -F= -v rel="$rel_contract" -v shape="$shape" '
        $1 == "owns[]" {
          print substr($0, index($0, "=") + 1) "|" rel "|" shape
        }
      ' >> "$contract_rows_tmp"
    fi
  done
fi

# Python handles duplicate detection and table-row generation using the
# already-normalized line protocol rows from yaml-lite.sh. No external
# Python packages are imported.
table_rows=$(python3 - "$ROOT" "$scripts" "$hooks" "$contract_rows_tmp" <<'PYEOF'
import sys

root = sys.argv[1]
scripts = [s for s in sys.argv[2].split("\n") if s]
hooks = [h for h in sys.argv[3].split("\n") if h]
contract_rows_path = sys.argv[4]

coverage = {}
errors = []

with open(contract_rows_path, encoding="utf-8") as rows:
    for raw in rows:
        line = raw.rstrip("\n")
        if not line:
            continue
        try:
            covered, contract_rel, shape = line.split("|", 2)
        except ValueError:
            continue
        if covered in coverage:
            errors.append(
                f"duplicate ownership: '{covered}' claimed by both {coverage[covered][0]} and {contract_rel}"
            )
        coverage[covered] = (contract_rel, shape)

if errors:
    for error in errors:
        print(f"DUPLICATE-OWNERSHIP: {error}", file=sys.stderr)
    sys.exit(1)


def row(rel):
    if rel in coverage:
        contract, shape = coverage[rel]
    else:
        contract, shape = "MISSING", "—"
    print(f"{rel}|{contract}|{shape}")


for script in scripts:
    row(f"scripts/{script}")
for hook in hooks:
    row(f".claude/hooks/{hook}")
PYEOF
)
py_rc=$?
[ $py_rc -eq 0 ] || { echo "generate-coverage: contract parsing failed" >&2; exit $py_rc; }

# Count MISSING rows in the regenerated table — used to emit the
# rollout-in-progress annotation only while the rollout is active.
# Once MISSING reaches zero (PR 7b's sweep), the annotation is omitted
# and the manifest is in steady state.
missing_in_table=$(printf '%s\n' "$table_rows" | grep -c '|MISSING|' || true)

# Emit the manifest
{
  echo "# Governance-script contract coverage"
  echo ""
  echo "<!-- AUTO — regenerated by scripts/generate-coverage.sh from filesystem scan. -->"
  echo "<!-- Sources: scripts/**/*.sh (excluding _* components), .claude/hooks/**/*.sh, docs/contracts/*.contract.md, docs/contracts/*.cli-contract.md -->"
  if [ "$missing_in_table" -gt 0 ]; then
    echo "<!-- Rollout in progress: MISSING rows will be covered by WS5 PRs 6 / 7a / 7b. -->"
  fi
  echo ""
  echo "| Script / Hook | Contract | Shape |"
  echo "|---|---|---|"
  while IFS='|' read -r rel contract shape; do
    [ -z "$rel" ] && continue
    echo "| $rel | $contract | $shape |"
  done <<<"$table_rows"
} > "$OUT"

exit 0
